### ISSUE TITLE
Antarctica/Troll fails to convert with TZConvert.GetTimeZoneInfo

### ISSUE THREAD

**Issue by ademchenko** [mattjohnsonpint/TimeZoneConverter#101] opened 2021-06-25 12:13 UTC
TimeZoneConverter of version 3.5.0 contains "Antarctica/Troll" in TZConvert.KnownIanaTimeZoneNames. As far as I understand it should imply that TZConvert.GetTimeZoneInfo("Antarctica/Troll") call has to be successful. 
But: it raises TimeZoneNotFoundException in Windows 10 environment.

**Comment by bartlomiej1gorski** [comment] 2021-06-28 11:35
Duplicate of #62

**Closed** 2021-08-20 13:42 UTC
